plugins = []

headers = []

[functions]

[functions."*"]

[build]
  publish = "D:\\Code\\Janus\\jenus-front-end\\dist"
  publishOrigin = "ui"
  commandOrigin = "ui"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
