name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli  # Install Angular CLI globally

      - name: Install dependencies
        run: |
          npm install

      - name: Build the Angular application
        run: |
          ng build --configuration=production --output-path docs --base-href /jenus-front-end/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages

    permissions:
      contents: write
